### ISSUE TITLE
Needs to handle missing FAQ Managers group

### ISSUE THREAD

**Issue by mikevasiloff** [spsprinkles/faq#18]
When the FAQ web part is added to a new site collection, it does not properly handle the **FAQ Managers** group not existing. Instead, it just keeps spinning and "blocks" the page from being used.
![image](https://github.com/spsprinkles/faq/assets/8918397/61d8b83d-f56f-498f-9fae-7fb96c54f09e)

Unsure if the web part attempts to create this group or not, but it would need to account for users not having enough permissions to create groups as well. The web part should properly handle the above failure when the group doesn't exist, close the dialog, and show a message to inform the user within the web part.

**Comment by gudatta** [comment]
We need to check to see if the user has manage web permissions for the security component. Also, we need to update the install dialog to check to see if the user has manage list permissions for that component.

**Comment by gudatta** [comment]
@Dade-R  - I will update the framework and hand this over to you to create the appropriate error messaging to display.
